In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
from sklearn import datasets

In [14]:
data = datasets.load_iris()

In [22]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [18]:
X = data.data
y = data.target

In [24]:
final = pd.DataFrame(X,columns = data.feature_names)

In [87]:
final.shape

(150, 4)

In [25]:
from sklearn.model_selection import train_test_split

In [88]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

In [89]:
from sklearn.preprocessing import StandardScaler

In [90]:
scaler = StandardScaler()

In [91]:
#scaler.fit(X_train)

In [92]:
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [93]:
X_train

array([[-1.08609665,  0.94240132, -1.59186407, -1.56796162],
       [-0.45254027, -0.75115606,  0.05699769, -0.06630683],
       [ 0.56114993, -0.50921929,  0.91196305,  1.02580574],
       [-1.46623047, -0.02534576, -1.65293303, -1.70447569],
       [ 2.46181906,  1.91014839,  1.40051468,  0.88929166],
       [ 1.06799504,  0.45852778,  1.09516991,  1.29883388],
       [ 0.94128376, -0.02534576,  0.66768723,  1.29883388],
       [-1.97307557,  0.45852778, -1.71400198, -1.56796162],
       [ 1.82826269, -0.50921929,  1.21730782,  0.75277759],
       [-0.19911772, -0.75115606, -0.00407126, -0.47584905],
       [ 0.05430483, -1.9608399 ,  0.54554932,  0.20672131],
       [-0.57925154, -1.47696637, -0.24834708, -0.47584905],
       [-0.57925154, -1.47696637, -0.18727813, -0.33933498],
       [ 0.68786121, -0.02534576,  0.8508941 ,  0.61626352],
       [ 0.30772738, -0.50921929,  0.42341142,  0.61626352],
       [ 0.94128376, -1.2350296 ,  1.03410096,  0.61626352],
       [ 0.43443866, -1.

In [94]:
X_test

array([[-0.19911772,  2.39402193, -1.77507094, -1.56796162],
       [-0.45254027, -0.26728253, -0.30941603, -0.06630683],
       [-0.45254027, -0.02534576, -0.00407126, -0.06630683],
       [ 2.20839651, -0.99309283,  1.70585945,  1.29883388],
       [-0.57925154, -1.2350296 , -0.06514022, -0.06630683],
       [-1.21280792,  0.45852778, -1.77507094, -1.56796162],
       [-0.70596282,  0.94240132, -1.46972616, -1.56796162],
       [ 0.56114993,  0.45852778,  0.24020455,  0.20672131],
       [-1.08609665, -1.2350296 , -0.67582976, -0.33933498],
       [-1.46623047,  0.94240132, -1.34758826, -1.56796162],
       [-1.71965302,  0.94240132, -1.65293303, -1.43144755],
       [ 0.56114993, -0.26728253,  0.11806664, -0.06630683],
       [-1.46623047, -0.02534576, -1.65293303, -1.43144755],
       [ 1.19470631,  0.21659101,  0.48448037,  0.20672131],
       [-1.21280792, -2.44471344, -0.37048499, -0.47584905],
       [-0.57925154,  2.87789546, -1.65293303, -1.56796162],
       [-1.71965302,  0.

In [95]:
from sklearn.neighbors import KNeighborsClassifier

In [96]:
model = KNeighborsClassifier(n_neighbors = 3)

In [97]:
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [98]:
y_pred = model.predict(X_test)

In [99]:
from sklearn.metrics import confusion_matrix,classification_report

In [100]:
confusion_matrix(y_test,y_pred)

array([[24,  0,  0],
       [ 0, 14,  0],
       [ 0,  0,  7]], dtype=int64)

In [101]:
classification_report(y_test,y_pred,output_dict = True)

{'0': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 24},
 '1': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 14},
 '2': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 7},
 'accuracy': 1.0,
 'macro avg': {'precision': 1.0,
  'recall': 1.0,
  'f1-score': 1.0,
  'support': 45},
 'weighted avg': {'precision': 1.0,
  'recall': 1.0,
  'f1-score': 1.0,
  'support': 45}}